### ISSUE TITLE
Steuern der Datenpunkte nicht möglich

### ISSUE THREAD

**Issue by FlexerJR** [t4qjXH8N/ioBroker.gardena#11]
Heute habe ich mir den Gardena Adapter installiert. In meinem System sind Folgende Komponenten. 

Gateway
Wassersensor
Wasseranschluss

Automower 330X mit Connect Modul. 

Der Automower ist über die Gardenaapp erreichbar und auch steuerbar. 

Es wäre klasse wenn man die States der eizelnen Geräte schalten könnte. 

Viele Grüsse

**Comment by t4qjXH8N** [comment]
Hallo FlexerJR, 

welche Datenpunkte willst Du steuern? Von welchem Gerät?

**Comment by t4qjXH8N** [comment]
Werden Datenpunkte für die Geräte angelegt?

**Comment by FlexerJR** [comment]
Hallo und guten Morgen. Manchmal sitzt das Problem vor dem Bildschirm. Ich hatte das anlegen der Datenpunkte nicht aktiviert. 

Ich sehe von allen Geräten alle Punkte. 

Jedoch verstehe ich nicht wie ich bei meinem Water Control mitteilendas Ventil zu öffnen. 

Ich habe  

button manual override 
Manual override
Valve open. 
und weite wie name oder id

Welchen Datenpunkt muss ich wie schalten dass Wasser fließt?

Ein schalten von valve open in ioBroker klappt nicht. 

Schalte ich über die Gardena App wird in den Datenpunkten korrekt angezeigt. 

Viele Grüsse

**Comment by t4qjXH8N** [comment]
Hey,
da müsste man das Kommando aus der Kommunikation zwischen App und Cloud ermitteln. In der Readme ist das für Android beschrieb, für IOS kenne ich leider keine App dafür.

Nach kurzer Google-Suche habe ich für IOS diese App [https://www.charlesproxy.com/documentation/ios/](https://www.charlesproxy.com/documentation/ios/)  
gefunden, vielleicht ist es damit möglich?

Eine kurze Rückmeldung wäre super, dann  kann ich die Methode für IOS zur Readme hinzufügen.

**Comment by t4qjXH8N** [comment]
Die Antwort kam per Mail. Danach ist die App nicht dafür geeignet. Die Ermittlung des Post-Kommandos ist nicht mehr gewünscht/nötig.

**Comment by FlexerJR** [comment]
Oh ich sehe das Issue ist geschlossen. Leider konnte ich das Kommando nicht auslesen. Anscheinend kam die Antwort von einem anderen User. Wann kann man denn mit einem Update rechnen?

**Comment by t4qjXH8N** [comment]
Hey,
ich kann den Adapter erst Updaten wenn ich das POST-Kommando kenne oder Gardena seine API offengelegt hat.

**Comment by FlexerJR** [comment]
Ok dann werde ich es nochmal versuchen kann nur einen moment dauern melde mich aber definitiv

**Comment by dirk99** [comment]
bei mir wird unter mower ein Datenpunktordner command angelegt, bleibt aber leer. Kein Objekt zum steuern. Wie kann das post Command mitgeschnitten werden? Ist eine https communication. hierfür müsste die App das entsprechende root Zertifikat installiert bekommen. Woher kann ich das bekommen?

**Comment by t4qjXH8N** [comment]
Bitte die Readme zum Adapter lesen.

**Comment by dirk99** [comment]
Hallo,

das Readme habe ich gelesen, danach sollte mein Selena mover ja funktionieren, da die in der JSON Datei enthalten sind. Die Datenpunkte werden aber nicht angelegt und sind somit nicht nutzbar.

Gruß
Dirk

Christian Vorholt <notifications@github.com> schrieb am 14.04.2019:

**Comment by t4qjXH8N** [comment]
Stimmt denn die category deines Rasenmähers mit der category in der Json
überein?

**Comment by dirk99** [comment]
Ja die Category stimmt überein, aber trotzdem 

 



 



 

Unter mower – commands – keine Einträge

 



 

Von: Christian Vorholt <notifications@github.com> 
Gesendet: Sonntag, 14. April 2019 16:34
An: t4qjXH8N/ioBroker.gardena <ioBroker.gardena@noreply.github.com>
Cc: dirk99 <howold@gmx.de>; Comment <comment@noreply.github.com>
Betreff: Re: [t4qjXH8N/ioBroker.gardena] Steuern der Datenpunkte nicht möglich (#11)

 

Stimmt denn die category deines Rasenmähers mit der category in der Json
überein?

dirk99 <notifications@github.com <mailto:notifications@github.com> > schrieb am So., 14. Apr. 2019, 16:25:

**Comment by dirk99** [comment]
Ich habe jetzt von den triggern den Schreibschutz entfernt und kann jetzt auch steuern. Danke
