### ISSUE TITLE
Adapter erzeugt keine device-Node in objects - gardena.0

### ISSUE THREAD

**Issue by janschmidt76** [t4qjXH8N/ioBroker.gardena#13]
Hallo,

ich habe vor ein paar Tagen von Version 1.1.0 auf 2.1.0 aktualisiert. Die Verbindung zur RESTful-API scheint zu funktionieren, die locations-Node wird angelegt. Allerdings fehlen alle devices - in meinem Fall der Gateway und der Rasenmäherroboter. Unter der Version 1.1.0 funktionierte das problemlos. Im iobroker-Log ist nichts zu finden. Kann ich das Problem irgendwie debuggen?

Viele Grüße
Jan

**Comment by t4qjXH8N** [comment]
Hallo Jan, 

was heißt "fehlen" genau? Werden keine Devices im Admin-Interface angezeigt? 
Bitte beachte, dass ab Version 2 die Devices im Admin-Interface explizit ausgewählt werden müssen.

**Comment by janschmidt76** [comment]
Hallo Christian,

jetzt siehst du mich verwirrt :-) Fehlen heißt, dass es überhaupt keinen Knoten für Devices unter gardena.0 in den Objects gibt. Wie komme ich denn zu dem Admin-Interface? In der Instance-Seite wird kein Button für eine Adapter-Webseite angezeigt. Im Readme steht dazu leider auch nichts...

**Comment by t4qjXH8N** [comment]
In der Adapterkonfiguration gibt es zwei Reiter: Haupteinstellungen und Datenpunkte. Unter Datenpunkte können die Datenpunkte ausgewählt werden, für die Objekte angelegt werden sollen.

**Comment by janschmidt76** [comment]
Wenn ich die Adapterkonfiguration aufrufe erscheint nur eine Seite "Gardena Smart System Einstellungen" die die Anmeldedaten abfragt. Keine weiteren Registerkarten. Kann da etwas von der alten Version über geblieben sein? Ich habe damals die alte Instanz (1.1.0) normal gelöscht und den alten Adapter deinstalliert. Danach dann die neue Version über den GitHub-Link installiert und die Instanz neu angelegt. Inzwischen habe ich auch die neue Instanz bereits einmal gelöscht und neu angelegt - leider ohne Erfolg, keine Registerkarten.

**Comment by t4qjXH8N** [comment]
Uploade bitte die Konfig neu. 

Das geht aus dem Admin-Interface im Reiter Adapter (Experteneinstellungen aktiviert) oder durch das Kommando

iobroker upload gardena

**Comment by janschmidt76** [comment]
Danke! Das hat geholfen. Jetzt noch meine VIS und Javascripts auf die neue Struktur anpassen, dann kann die Saison wieder starten :-)
Vielen Dank für die Unterstützung!
