### ISSUE TITLE
Datenpunkte werden nicht angelegt

### ISSUE THREAD

**Issue by eumats** [t4qjXH8N/ioBroker.gardena#14]
Hallo,

nach der Winterpause habe ich den gardena Adapter wieder auf meinem Raps installiert und gestartet. Leider werden aber die Datenpunkte für die Devices nicht mehr angelegt. 
Vor der Einbettung des Mähroboter hat das Ganze noch funktioniert. Dort war dann die Datenpunkte für die Gateway, den Mähroboter und den Sensor zur sehen.
Die Änderung zum Vorjahr:
1. Adapter neu installiert (Version 2.0.1)
2. Firmwareupdate Mähroboter Sileno

Hier die Log des Adapter im "silly" Modus:
> `gardena.0	2019-03-22 15:45:22.494	info	Retrieved device data.
gardena.0	2019-03-22 15:45:22.485	info	Retrieved device data.
gardena.0	2019-03-22 15:45:22.029	debug	Retrieved all locations.
gardena.0	2019-03-22 15:45:22.029	info	Updated locations in the database.
gardena.0	2019-03-22 15:45:21.644	debug	Change in connection detected, setup polling if true.
gardena.0	2019-03-22 15:45:21.644	debug	stateChange gardena.0.info.connection {"val":true,"ack":false,"ts":1553265921605,"q":0,"from":"system.adapter.gardena.0","user":"system.user.admin","lc":1553265824519}
gardena.0	2019-03-22 15:45:21.636	silly	inMem message gardena.0.info.connection gardena.0.info.connection val=true, ack=false, ts=1553265921605, q=0, from=system.adapter.gardena.0, user=system.user.admin, lc=1553265824519
gardena.0	2019-03-22 15:45:21.607	info	Polling locations.
gardena.0	2019-03-22 15:45:21.605	debug	Saved auth tokens.
gardena.0	2019-03-22 15:45:21.602	debug	Response: OK
gardena.0	2019-03-22 15:45:21.074	info	Connecting to Gardena Smart System Service ...
gardena.0	2019-03-22 15:45:21.072	info	Starting gardena smart system adapter
gardena.0	2019-03-22 15:45:21.025	info	starting. Version 2.0.1 in /opt/iobroker/node_modules/iobroker.gardena, node: v6.13.1
`

**Comment by t4qjXH8N** [comment]
Bitte lese das geschlossene issue 13 durch und teste ob es geht.

**Comment by eumats** [comment]
Das hatte ich vor meinen Post bereits gemacht. Das hatte ich nur vergessen zu schreiben.
Also ein "iobroker upload gardena" bringt bei mir leider nix...
Ich habe die Adapter auch mal de- und wieder installiert. Leider auch ohne Erfolg.

**Comment by t4qjXH8N** [comment]
Ok, sind denn in der Instanz im Admininterface Datenpunkte ausgewählt worden? Da ist ein Reiter der heißt Datenpunkte. Die Datenpunkte sind opt-in.

**Comment by eumats** [comment]
Ne, das hab ich nicht. Das muss neu sein und habe ich übersehen...
Jetzt die die Datenpunkte unter Objekte da. Zwar anders strukturiert als vorher, aber egal.
Danke für die Hilfe.

PS: Eine Frage: Was sind denn "intelligente Datenpunkte"?

**Comment by t4qjXH8N** [comment]
Das ist auch neu. Der Adapter ist jetzt viel schneller und effizienter.

Was intelligente Datenpunkte sind steht in der Adapter README.md.

Die Problematik mit dem Reiter Datenpunkte wurde bereits im issue 13 erwähnt.

Ist das Issue damit gelöst?

**Comment by eumats** [comment]
Ja. Besten Dank!
