### ISSUE TITLE
Datenpunlkte werden nicht angelegt

### ISSUE THREAD

**Issue by dirk99** [t4qjXH8N/ioBroker.gardena#15]
Ich habe gerade den Adapter neu installiert in der Version 2.01. Es werden die Datenpunkte von Riesenroboter nicht mehr angelegt. Es wird  nur die locations und info angelegt. Unter Info ist die Connection auf true. In der Gardena APP ist die Kommunication mit dem Gateway/Mover o.k. Den Tip mit dem Upload aus dem Thread#13 habe ich schon versucht, doch leider ohne Erfolg. Hat Gardena eventuell den Restaufruf geändert? Der Mover hat auch ein Softwareupdate hinter sich. Die App hat gegenüber dem letzten Jahr auch Änderungen...

**Comment by t4qjXH8N** [comment]
Ich fasse mich kurz: issue 14 gelesen?

**Comment by dirk99** [comment]
Daumen hoch. Der Tab ist aber erst nach vollständiger Deinstallation (löschen des Admininterface unter /opt/iobroker/iobroker-data) und Neuinstallation hinzugekommen. Hmmm. Danke für den schnellen Support

**Comment by t4qjXH8N** [comment]
Alles klar!
