### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by domi1989** [t4qjXH8N/ioBroker.gardena#16]
Error during Installation
![1111](https://user-images.githubusercontent.com/49128703/55293700-8253c180-53f9-11e9-987d-50ff7f17b7a7.JPG)

**Comment by t4qjXH8N** [comment]
This command is working properly on my system, please check internet access or your npm installation

**Comment by domi1989** [comment]
which npm version do i need? i see there is a update for npm, can i update it without any issues?

![1111](https://user-images.githubusercontent.com/49128703/55293846-3013a000-53fb-11e9-8d9b-50ec27084949.JPG)

**Comment by t4qjXH8N** [comment]
You are using a quite old version. Sorry, I do not know if there will be any issues.

**Comment by domi1989** [comment]
after updating npm, adapter is running, thank you for your support
