### ISSUE TITLE
Komische Gruppen wurden erzeugt

### ISSUE THREAD

**Issue by neopholus** [t4qjXH8N/ioBroker.gardena#18]
Hallo,

gerade mir ioBroker angefangen und sehr begeistert. Danke für die viele Arbeit, die ihr investiert. Ich habe meinen Mähroboter eingebunden, hat auch gleich geklappt. 

Komisch finde ich nur, dass in der Benutzerverwaltung von ioBroker jede Menge Gruppen angelegt werden, z.B. folgende Gruppe:
- Name: park_until_further_notice
- ID: park_until_further_notice
- Vorschau: gardena.0.datapoints.7b6b24cd-0830-4059-be05-872a31c9f4db.c541f6eb-4b1e-4861-8430-4b566c49d535.abilities.mower.command.park_until_further_notice

Ich vermute mal, damit hätten Datenpunkte gruppiert werden sollen, es wurden aber aus Versehen Gruppen in der Userverwaltung angelegt?

Tritt das Problem noch bei jemand anderem auf?

Viele Grüße
Stefan

**Comment by neopholus** [comment]
Anbei ein Screenshot des Problems:

![AddedUserGroups](https://user-images.githubusercontent.com/39877538/55921396-d716e980-5bfc-11e9-99ce-72aaaf88d28e.png)

Hinweis: Löschen geht bei vielen Gruppen gar nicht, da sie keinen Namen haben....

**Comment by t4qjXH8N** [comment]
Hallo Stefan, 

es stimmt, das ist ein Fehler. Ich benutze das group-Tag in der Hoffnung das dieses zur Gruppierung von States genutzt werden kann. Das war wohl so nicht vorgesehen, vielmehr handelt es sich wohl um usergroups. Meines Wissens ging das aus der Entwickler-Doku so nicht hervor. Ich Patche das kurzfristig, das ist tatsächlich sehr nervig.

**Comment by neopholus** [comment]
Hallo Christian,

sehr nett von dir, danke schon mal. 
Hast du zufällig noch eine Ahnung, wo im Dateisystem die Usergruppen gespeichert werden? Da ich die Gruppen in der GUI nicht mehr löschen kann, würde ich die gerne manuell löschen...

Viele Grüße
Stefan

**Comment by t4qjXH8N** [comment]
Hey, 

kannst Du das bitte testen? Die Version liegt im topic-#18 Branch. Ich vermute, Du musst die alte Version vollständig entfernen.

**Comment by t4qjXH8N** [comment]
Die Gruppen sollten verschwinden, wenn Du die Objekte löschst.

**Comment by neopholus** [comment]
- Nach dem Löschen von Instanz, Adapter und Objekten sind die Gruppen weg. 
- Muss noch kurz nachsehen, wie man in ioBroker einen Branch installieren kann. Mit der URL https://github.com/t4qjXH8N/ioBroker.gardena/issues/18 ging es schon mal nicht ;-)

**Comment by neopholus** [comment]
Hallo Christian,

leider klappt es irgendwie nicht. Ich habe von [https://codeload.github.com/t4qjXH8N/ioBroker.gardena/zip/topic-%2318](url) das ZIP-File nach /tmp/ heruntergeladen. Dann unzip darauf aufgerufen, das Verzeichnis schreibbar gemacht und dann in IOBroker per "Adapter aus beliebiger Quelle installieren oder aktualisieren" installiert.

Die Installation scheint geklappt zu haben:
`$ ./iobroker url "/tmp/ioBroker.gardena-topic-18/"
install /tmp/ioBroker.gardena-topic-18/
npm install /tmp/ioBroker.gardena-topic-18/ --production --save --prefix "/opt/iobroker" (System call)
process exited with code 0`

Dann im Adapter auf "Upload" geklickt, eine Instanz angelegt und konfiguriert.

Nun gibt es Probleme:

1. Verbindungsprüfung funktioniert nicht -- es tut sich einfach nichts
2. Unter "Datenpunkte" wird nichts angezeigt
3. Im Log steht:
`host.ioBroker | 2019-04-13 19:37:34.168 | error | instance system.adapter.gardena.0 terminated with code 10 (Cannot find start file of adapter)
-- | -- | -- | --`

**Comment by t4qjXH8N** [comment]
Habe es getestet, bei mir geht es.

**Comment by neopholus** [comment]
Hallo Christian,

1000 Dank. Vom master installiert hat es bei mir auch geklappt. Die Gruppen werden nicht wieder angelegt, funktioniert also nun, wie es soll.

Schönes Wochenende noch
Stefan
