### ISSUE TITLE
Configurable API URL

### ISSUE THREAD

**Issue by SciLor** [t4qjXH8N/ioBroker.gardena#21]
It would be nice to have the api url configurable, as I am currently working on a project to replace the cloud with a local script running on the gateway.

**Comment by t4qjXH8N** [comment]
Sounds interesting! Do you have a link to the project?

**Comment by SciLor** [comment]
https://github.com/gardena-smart-reverse-engineering/deGardenServer/tree/develop

**Comment by t4qjXH8N** [comment]
api url can be configured now

**Comment by t4qjXH8N** [comment]
Do you have any idea how to find out which POST commands and their respective attributes are supported by the service?

**Comment by SciLor** [comment]
Great, thank you.

I am not really that far, that I understand the write commands to the devices/services.

That may be extraced from the service definition that is available from the devices connected to the gateway.
But the gardena cloud itself maps/filters it.
You may retrieve the service definitions of the gardena cloud, too. They are just simple jsons you can sniff from the gardena cloud websites data traffic.
I am not that far that I understand writing to the devices completly.

**Comment by t4qjXH8N** [comment]
Some months ago it was possible to sniff the communication between the Gardena app and the gardena service. Sadly, this is not possible anymore (at least with the app which was quite easy). Maybe I should ask the Gardena service if they could help?

**Comment by SciLor** [comment]
Just use https://smart.gardena.com/ to get your communication logs.
