### ISSUE TITLE
Feature request: Update triggern

### ISSUE THREAD

**Issue by neopholus** [t4qjXH8N/ioBroker.gardena#22]
Hallo Christian,

eine Bitte: Ich habe das Update-Intervall auf 600 Sekunden stehen. Im Normalfall ist das vollkommen ausreichend. Wenn ich aber nun einen Befehl an den Mähroboter schicke, z.B. dass er parken soll, würde ich gerne für die nächsten 2 Minuten das Update öfter triggern können, z.B. alle 10 Sekunden (um zu sehen, wann der Roboter auf den Befehl reagiert, wann er die Ladestation sucht und wann er in der Ladestation angekommen ist).

Ich habe keine Möglichkeit gefunden, das bei deinem tollen Adapter zu machen. Ich stelle mir einen Datenpunkt vor, der man auf true setzt. Daraufhin liest der Adapter die Daten neu von Gardena aus und setzt den Datenpunkt wieder auf false.

Meinst du, das ist möglich? Oder gibt es vielleicht schon eine Möglichkeit, die ich nicht gefunden habe?

Viele Grüße und vielen Dank
Stefan

**Comment by irudi** [comment]
Ich finde das eine gute Idee.. Gerade beim Testen wünscht man sich, dass man mal ein Update erzwingen kann!

**Comment by t4qjXH8N** [comment]
Ich finde das auch gut .... Werde mich mal dransetzen

**Comment by t4qjXH8N** [comment]
Es gibt jetzt einen passenden Branch zum Issue. Könnte bitte jemand diesen Branch testen?

**Comment by irudi** [comment]
Hm ... ich bin auf dem additional_devices branch wegen des Supports für das watering outlet. Kannst Du den da bitte mit rein mergen, dann probiere ich das gerne aus

**Comment by t4qjXH8N** [comment]
Tut denn das watering outlet?

Rudi <notifications@github.com> schrieb am Fr., 28. Juni 2019, 08:40:

**Comment by neopholus** [comment]
> 
> 
> Ich finde das auch gut .... Werde mich mal dransetzen

Hallo Christian,

mit so einer schnellen Reaktion habe ich im Traum nicht gerechnet. Leider kann ich aktuell nicht testen, weil ich noch eine Woche unterwegs bin. Danach teste ich gerne. Sorry,,,

Viele Grüße und vielen Dank
Stefan

**Comment by irudi** [comment]
Ja, das funktioniert.

**Comment by t4qjXH8N** [comment]
Alles klar. Ich update den Master.

**Comment by neopholus** [comment]
Klappt super, vielen herzlichen Dank!
