### ISSUE TITLE
webservice base url?

### ISSUE THREAD

**Issue by vowchr** [t4qjXH8N/ioBroker.gardena#23]
Version 2.4.0 - webservice base url can be freely configured

Und was muss hier eingetragen werden? Wie lautet die URL von Gardena?

Danke für die Hilfe!

**Comment by t4qjXH8N** [comment]
Das Feld sollte nur leer sein, wenn man direkt über Git updated. Die Base-URL steht in der io-package.json und lautet https://sg-api.dss.husqvarnagroup.net

**Comment by vowchr** [comment]
Danke für die Info. Funktioniert leider nicht bei mir - connection failed :-(

**Comment by vowchr** [comment]
Wenn ich versuche, mich direkt unter https://sg-api.dss.husqvarnagroup.net/ einzuloggen erhalte ich "Serverfehler. Bitte versuche es später nochmal".
Wenn ich mich direkt unter https://smart.gardena.com/ einlogge funktioniert es.

Aber https://smart.gardena.com/ webservice base url zu verwenden klappt auch nicht :-(

**Comment by t4qjXH8N** [comment]
Die Fehlermeldung auf https://sg-api.dss.husqvarnagroup.net/ ist doch eindeutig?

**Comment by vowchr** [comment]
Naja, müssten dann nicht alle anderen auch Probleme haben weil der Adapter nicht funktioniert?

**Comment by t4qjXH8N** [comment]
Ja, müsste so sein.
