### ISSUE TITLE
send command

### ISSUE THREAD

**Issue by dupan99** [t4qjXH8N/ioBroker.gardena#5]
which command is needed to execute i.E water flow?

**Comment by t4qjXH8N** [comment]
To be honest, I don't know because I do not have a water flow. 

If you could sniff the communication of the app with the gardena cloud when the water flow is enabled I could add this functionality to the gardena adapter.

For sniffing I made good experiences with the app [Packet Capture](https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture&hl=en) for android.

**Comment by dupan99** [comment]
command: button 2 minutes water flow

-------------------------------
-------------------------------


PUT /sg-1/devices/b9daaed1-c0c4-4514-a520-879b2a3994d6/abilities/outlet/command?locationId=4192f960-1a40-4c11-9b4d-898ee32ab550 HTTP/1.1


{"name":"manual_override","parameters":{"manual_override":"open","duration":2}}HTTP/1.1 204 No Content
Date: Mon, 16 Jul 2018 04:55:22 GMT
Connection: keep-alive
X-Rate-Limit-Limit: 6300
X-Rate-Limit-Remaining: 6296
X-Rate-Limit-Reset: 2




PUT /sg-1/devices/b9daaed1-c0c4-4514-a520-879b2a3994d6/abilities/outlet/properties/button_manual_override_time?locationId=41924960-1a40-4c11-9b4d-890d562ab550 HTTP/1.1

{"properties":{"name":"button_manual_override_time","value":2,"timestamp":"2018-07-16T04:33:09.122Z","at_bound":null,"unit":"minutes","writeable":true,"supported_values":[],"ability":"69905a98-20a3-4bfd-8e95-9eb5f6c08c90"}}HTTP/1.1 204 No Content
Date: Mon, 16 Jul 2018 04:55:24 GMT
Connection: keep-alive
X-Rate-Limit-Limit: 6300
X-Rate-Limit-Remaining: 6296
X-Rate-Limit-Reset: 1

**Comment by t4qjXH8N** [comment]
What is the value of "gardena.0.[deviceid].category"?

**Comment by dupan99** [comment]
The Value is gardena.0.[deviceid].category.  ...watering_computer ...

here a screenshot:

<img width="1292" alt="bildschirmfoto 2018-08-10 um 17 50 13" src="https://user-images.githubusercontent.com/21146175/43968347-1f766e26-9cc7-11e8-966e-60a1b5499bd9.png">

**Comment by dupan99** [comment]
Hallo, gibt es schon etwas neues zwecks Unterstützung für das senden von Kommandos?

**Comment by t4qjXH8N** [comment]
Hey,

ich bin dabei eine komfortable und generische Lösung zu erarbeiten. Leider habe ich im Moment wenig Zeit, daher vermute ich mal das es noch zwei Wochen dauern wird.

**Comment by t4qjXH8N** [comment]
Könntest Du testen, ob das Ventil mit der aktuellen Version 2.0.0 funktioniert?

**Comment by domi1989** [comment]
Hallo, habe aktuell Version 2.0.1, sehe in den Objekten die Datenpunkte, aber nichts mit dem ich das Ventil steuern kann. Wenn ich das richtige verstehe, muss ich zuerst die Daten auslesen, was die Gardena app schickt entschlüsseln, oder? Ich habe nun die Packet capture installiert, aber sobald ich diese aktivere, kommt eine VPN verbindung und die Gardena app ist offline. Gibt es noch alternativ apps? Gruß Dominik

**Comment by diebacke** [comment]
@t4qjXH8N 
Hallo Christian,
das gleiche Problem hab ich mit der App Packet Capture auch. Sobald ich sniffe, kommt die Gardena App nicht mehr raus. Hast Du eine Idee?

Ich habe einen Gardena Smart Sileno City 500 und möchte diesen gern über io.Broker starten und zur Ladestation schicken.

Hast Du eine Alternative parat, um an die DeviceID und die LocationID zu kommen?

Grüße,
Stefan

**Comment by vowchr** [comment]
Gibt es hierzu schon News? Ich sehe zwar die Variablen bezüglich Water Control, wenn ich sie aber via IO Broker setze wird das ignoriert - beim nächsten Polling wird es wieder zurückgesetzt. 
Wirkt fast so, wie wenn nur readonly möglich wäre 😞

Gibts auch Sniffer für iOS? Würde gerne mithelfen!

**Comment by t4qjXH8N** [comment]
Hast du die aktuelle Version von gestern?

**Comment by t4qjXH8N** [comment]
Und welche category wird bei Dir angezeigt?

**Comment by vowchr** [comment]
Hm, gute Frage... Also im IOBroker wird beim Adapter die Version 1.2.0 ausgegeben - da aber kein Update gefunden wird denke ich schon das ich auf der aktuellen Version bin.

Als category wird watering_computer ausgegeben.

**Comment by t4qjXH8N** [comment]
Die Version kann aber nicht stimmen... Die ist schon sehr alt. Es wäre gut, wenn wir einen neues Issue aufmachen, da jetzt unklar ist, ob das Smarte Ventil (smart Water Control) oder der Smarte Bewässerungscomputer (smart Irrigation Control) gemeint ist. Daher bitte ich um die Anlage eines neuen Issue. Zudem befinde sich im Branch "addtional devices" eines Version, welche vielleicht den "watering_computer" ansteuern kann.

**Comment by vowchr** [comment]
Danke für den Hinweis - bin jetzt auf Version 2.1.1. Funktioniert aber weiterhin nicht.
Was sonderbar ist: Via ioBroker  Admin-Oberfläche werden für den Gardena Adapter bei mir nur die Versionen bis 1.2.0 gelistet. Den Upgrade konnte ich nur direkt von GIT hier machen.
Nutze als Repository "latest" (http://download.iobroker.net/sources-dist-latest.json)

Betreffend deinem Hinweis mit dem Branch "addtional devices" - wie kann ich diesen den installieren?

**Comment by t4qjXH8N** [comment]
Naja, der gardena Adapter sollte gar nicht im io Broker repository sein,
wahrscheinlich war das der letzte Stand von git oder npm.

Welches Gerät has du denn genau? Den Branch kann aus git installieren, da
muss nur der Branch angegeben werden.

>

**Comment by vulli2000** [comment]
Hallo und guten Abend.
Erst einmal vielen Dank für die Einbindung des "Water Control" in den Gardena-Adapter. Die Installation der Version 2.2.0 hat super geklappt, sodass mir nun die folgenden und zusätzlichen Objekte unter "/outlet/command/" angezeigt werden:
![grafik](https://user-images.githubusercontent.com/50716841/57880865-29f94780-7820-11e9-8d4d-61856add1eff.png)
Wie soll das nun funktionieren? Gibt es eine kleine Anleitung zum Setzen des "triggers", sodass die "Water Control" den Wasserfluss für die eingestellte Zeit startet?
Meine manuellen Versuche über das Objekt haben bisher noch nicht funktioniert. :-(
Vielen Dank und viele Grüße....

**Comment by t4qjXH8N** [comment]
Das Water-Control ist experimentell, ich habe es leider nicht hier und kann es nicht testen. Schade, ich habe die Ressourcen aus einem anderen Projekt übernommen. Würdest du ein paar Versionen testen? Wie ist der Stand, also es tut gar nicht? Kannst du mir das Debug-Log schicken?

**Comment by vulli2000** [comment]
Hallo, gerne kann ich ein paar Versionen testen :-). Wäre ja super, wenn sich das Water Control ansteuern lassen würde...
Um das Water Control zu triggern setze ich in den Objekten des Gardena-Adapters den Trigger <manual_override> auf den Wert "true". Nach dem Speichern springt der Wert sofort wieder auf "false":
![grafik](https://user-images.githubusercontent.com/50716841/57986663-1c3dff00-7a78-11e9-8f5c-43a62d65c12b.png)
In der Log und/oder in den Ereignissen des iobrokers passiert dabei gar nichts. Ist der Trigger von mir denn richtig gesetzt? Und wo wird das Debug-Log geschrieben?
Vielen Dank und einen schönen Abend...

**Comment by vulli2000** [comment]
Hallo und guten Abend.
Ich habe nun das Log-Level des adapters "Gardena.0" auf debug gesetzt und den Trigger auf "true" gesetzt.
Der Trigger ist sofort wieder auf "false" zurückgesprungen und das angefügte LOG wurde geschrieben.
[gardena.0_debug.log](https://github.com/t4qjXH8N/ioBroker.gardena/files/3208438/gardena.0_debug.log)
Das Kommando zum Schalten wird per HTTP gesendet, doch leider kommt hier ein Fehler zurück...
Hilft diese Information weiter?
Vielen Dank und viele Grüße...

**Comment by vulli2000** [comment]
Hallo und guten Abend.
Gibt es etwas Neues? Konnte das Debug-Log weiterhelfen?
Vielen Dank und viele Grüße,

**Comment by maodch** [comment]
Hallo zusammen
ich wäre auch brennend an einer Lösung interessiert, mit welcher die Smart Irrigation Control resp. die 24V Ventile gesteuert werden könnten.
Schön wäre einfach, wenn man pro Watering_Timer ein true werfen könnte :-)

**Comment by irudi** [comment]
Kurze Rückmeldung: wenn man die Duration auf einen sinnvollen Minuten-Wert setzt (bei mir stand dort initial 1440 drin ...), dann funktioniert der Start der Bewässerung über den Trigger! 👍

**Comment by vulli2000** [comment]
Perfekt, habe auch den Wert von duration auf "8" gesetzt und es funktioniert :-)

**Comment by maodch** [comment]
irudi, hast du mir mal einen Printscreen, welcher Trigger da funktioniert?
Bei mir gibt es die duration, state, valve_id, watering_timer_1
Da kann ich bei der duration reinschreiben was ich will.
Aber ich glaube, dann tut die "smart irrigation control" einfach nicht.

**Comment by vulli2000** [comment]
![grafik](https://user-images.githubusercontent.com/50716841/60300152-a5c1d600-992e-11e9-8d5a-7ab6e41dec8a.png)

**Comment by vulli2000** [comment]
Bitte schön...
Duration einfach "Im Dialog bearbeiten". So kann auch der Trigger auf true gesetzt werden. Hilf dieses weiter?

**Comment by maodch** [comment]
Wenn ich da 60 reinschreibe (nicht bestätigt) kommt eine Sekunde später "false"
Mach ich 60 (bestägigt), dann passiert gar nichts

**Comment by maodch** [comment]
glaube, das funktioniert nicht wirklich.
Passiert weder in der App noch draussen im Garten was.
Schade

**Comment by t4qjXH8N** [comment]
Die Smart Irrigation Control funktioniert auf jeden Fall. Zumindest das 4-Ventile System, ich nutze es gerade. Müsste mal nachgucken was man da setzen musste, das ist ziemlich tief in meinen Javascripts drin ... Sonst bitte auf Debug stellen und das Log posten

**Comment by maodch** [comment]
![grafik](https://user-images.githubusercontent.com/33425357/60301949-dc015480-9932-11e9-960f-0d75b650b384.png)

**Comment by maodch** [comment]
Sieht so bei mir aus ...
![grafik](https://user-images.githubusercontent.com/33425357/60302028-18cd4b80-9933-11e9-8ba2-3c8a46228713.png)

**Comment by maodch** [comment]
Also ich nutze die Smarcontrol mit 6 Kanälen (2 Ventilboxen à 3 Ventile 24V), liefere gleich das Debug

**Comment by maodch** [comment]
habe am true und an der duration rumprobiert, ohne bestätigt tut sich was, mit, passiert nicht mal eine response
![grafik](https://user-images.githubusercontent.com/33425357/60303680-57fd9b80-9937-11e9-8081-77be79340a51.png)

**Comment by maodch** [comment]
denke, das "answer undefined" ist wohl der Übeltäter

**Comment by domi1989** [comment]
ich habe das water control, ich steuere es einfach über ifttt an (mit webhooks und gardena), klappt einwandfrei. vielleicht ist das auch für euch eine Alternative ;)

![image](https://user-images.githubusercontent.com/49128703/60317352-f3f6c980-996e-11e9-9aaa-6570439b5d43.png)

**Comment by vulli2000** [comment]
Bei mir funktioniert das Water Control prima.
duration habe ich gleich 10 gesetzt und gespeichert. Wenn ich dann in trigger "true" schreibe springt dieser auch wieder auf "false" zurück (wohl normales verhalten), doch das Water Control bewässert für 10 minuten. Diesen Status sehe ich auch in der Gardena-APP 🥇 
Version 2.2.0 ist installiert...

**Comment by irudi** [comment]
Genau so mache ich das auch: in duration eine 10 und dann trigger auf true.

**Comment by maodch** [comment]
iftt ist für mich keine Option, möchte nicht noch ein weiteres Tool anlachen

Aber dann ist bei mir iwo was kaputt.
ich schreibe bei "duration" 10 rein, dann trigger true.
Dann bleibt die 10 stehen, der trigger geht von true auf false und dann passiert einfach nix.
auch nicht in der app.

mist :-(

**Comment by maodch** [comment]
keine Ahnung was bei euch anders ist als bei mir

**Comment by maodch** [comment]
wenn ich aber in der app die Bewässerung starte, dann sehr ich das in den Datenpunkten.

**Comment by maodch** [comment]
welche Version nutzt ihr?

**Comment by irudi** [comment]
Ich nutze das aus dem additional_devices branch

**Comment by maodch** [comment]
ahhh, wenn ich das via Skript anwerfe, dann tut es :-)
Spannend

Wie stoppt ihr die Bewässerung? 0 geht nicht, einfach auf 1 min?

**Comment by maodch** [comment]
sau komisch, jetzt habe ich noch ein paar Datenpunkte (Feuchtigkeitssensor) mit geladen, jetzt funktioniert wieder gar nichts mehr, auch nicht via code ...

Gebs glaub auf

**Comment by maodch** [comment]
also, jetzt hab ich des Rätsels Lösung:
state = "manual" ist bei mir zwingend, denn
state = "idle" stoppt die Bewässerung

**Comment by t4qjXH8N** [comment]
Vielleicht sollten wir diese Infos unter FAQs sammeln. Könnte jemand bitte
faq-tauglich erklären, welche Datenpunkte wie die für ein bestimmtes Gerät
gesetzt werden müssen? Das wäre klasse.

**Comment by t4qjXH8N** [comment]
Habe ein minimales Wiki angelegt.

**Comment by irudi** [comment]
Also ich habe mal die aktuelle Version getestet. Das mit dem manuellen Poll klappt prima. Leider funktioniert mein water outlet nicht mehr ...

**Comment by t4qjXH8N** [comment]
Bitte das debug log posten

**Comment by irudi** [comment]
Ok, da gibt es einen Fehler. Habe gerade noch mal den ganzen gardena Objekt-Baum gelöscht und neu erzeugen lassen - keine Änderung. 

`
2019-07-05 07:26:11.781 - debug: gardena.0 stateChange gardena.0.datapoints.6127be57-43f9-4a03-a9cc-9a1e999c0fde.ce209317-9fb7-4b47-87cc-1960bc090f49.abilities.outlet.command.manual_override.trigger {"val":true,"ack":false,"ts":1562304371774,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1562304371774}
2019-07-05 07:26:11.888 - debug: gardena.0 Sending command via HTTP post.
2019-07-05 07:26:11.888 - debug: gardena.0 URI: undefined/sg-1/devices/ce209317-9fb7-4b47-87cc-1960bc090f49/abilities/outlet/command?locationId=6127be57-43f9-4a03-a9cc-9a1e999c0fde
2019-07-05 07:26:11.888 - debug: gardena.0 Dataframe: {"name":"manual_override","parameters":{"manual_override":"open","duration":10}}
2019-07-05 07:26:11.889 - error: gardena.0 Could not send command to uri undefined/sg-1/devices/ce209317-9fb7-4b47-87cc-1960bc090f49/abilities/outlet/command?locationId=6127be57-43f9-4a03-a9cc-9a1e999c0fde.
2019-07-05 07:26:11.889 - error: gardena.0 An error occurred during trigger! 
`

**Comment by t4qjXH8N** [comment]
Danke,hast du die Dateien für das Admin-Interface neu hochgeladen? Also
z.B. iobroker upload gardena ausgeführt?

**Comment by t4qjXH8N** [comment]
Sollte in der 2.4.1 behoben sein.

**Comment by irudi** [comment]
Ok - gerade mal ein Update gemacht und erfolgreich getestet! Danke!

**Comment by t4qjXH8N** [comment]
Heißt das es geht jetzt?

**Comment by irudi** [comment]
Ja, das meinte ich mit "erfolgreich" getestet 👍

**Comment by maodch** [comment]
2.4.1 gibt es wo? Ich sehe überall nur 2.1.1?

Gibt es eigentlich auch die Möglichkeit, bei Garena nur einzelne Felder abzupollen wie z.B. den Watering-State?

Habe in ioBroker ein komplettes Skript, welche Regen, Sonne, Temperatur etc. Historisch und auch zukünftig auswertung und anhand dessen bewässert.
Was ich aber leider nicht habe ist den aktuellen Zustand:
Sprich, Start der Bewässerung und dann .... müsste ich den Poller auf 60s setzen, was aber auch absurd ist, nicht, dass Gardena dann noch die API verschärft.
Aber schön wäre zu wissen, wann die Bewässerung beendet ist. Somit könnte ich das in meiner App anzeigen, weiterhin könnte ich den exakten Wasserverbrauch berechnen etc.

**Comment by t4qjXH8N** [comment]
Sorry, dies ist kein Forum. Wenn ein Fehler auftritt, bitte ein neues Issue anlegen. Für einen Feature-Request bitte ebenso. Das macht es mir sonst echt schwer, den Überblick zu behalten. 

Die aktuelle Version kannst Du aus dem MasterBranch abholen. Es gibt ein Feld in dem steht, wie lange die Bewässerung noch dauert. Siehe Examples im Wiki.

**Comment by maodch** [comment]
Sorry, :-(

**Comment by t4qjXH8N** [comment]
Macht doch gar nix, leg einfach ein Issue oder ein Feature request an. Wie gesagt, alle deine Probleme sind bereits gelöst.

**Comment by maodch** [comment]
Aber ein Issue habe ich trotzdem :-)
Habe mir gerade die 2.5er installiert. Anfangs lief alles, dann aber plötzlich meinte der Adapter, er könne sich nicht mehr verbinden.
Keine Chance. Zig mal Neustart, ging nicht mehr.
Vorher Backup gemacht und zurückgespielt, alles wieder gut.
Also iwas scheint da noch nicht 100% zu sein.

**Comment by t4qjXH8N** [comment]
Danke für die Info, Debug einschalten,issue eröffnen und das Log mit
Fehlerbeschreibung posten.

**Comment by t4qjXH8N** [comment]
Hast du iobroker upload ausgeführt und die Einstellungen kontrolliert?
