### ISSUE TITLE
Ansteuerung Gardena Smart Power Adapter

### ISSUE THREAD

**Issue by tp1de** [t4qjXH8N/ioBroker.gardena#7]
Ich habe nun nach der Anleitung mit Packet Capture die Kommunikation protokolliert und herausgefunden wie ich den Smart Power Adapter ansteuern kann. Ich mache das wie immer unter Node-Red, da die Systembelastung des Adapters mir zu hoch ist. 

Unter Node-red mache ich alle 30 Minuten eine neue Session auf - mit Session Timeout von 60 Minuten - und frage mit http den Status alle 30 Sekunden ab. Das funktioniert seit Wochen problemlos.
(habe den Flow als Beispiel im ioBroker Forum hinterlegt)

Während der Sileno Mähroboter mit "Commands" und http POST angesteuert wird, wird der Power Adapter mit http PUT direkt in die "properties" Struktur beschrieben:

msg.payload = {"properties" :{ "value": "on"}};       
msg.payload = {"properties" :{ "value": "3600"}};   (eine Stunde)
msg.payload = {"properties" :{ "value": "off"}};

var url= "https://sg-api.dss.husqvarnagroup.net/sg-1/devices/" + _powerid_ + "/abilities/power/properties/power_timer?locationId= _xxxxx_";

Vielleicht hilft dies weiter.

Grüße Thomas

**Comment by t4qjXH8N** [comment]
Hey danke,

ich bin dabei eine komfortable und generische Lösung zu erarbeiten. Leider habe ich im Moment wenig Zeit, daher vermute ich mal das es noch zwei Wochen dauern wird.

**Comment by t4qjXH8N** [comment]
Könntest Du testen, ob der Smart Power Adapter mit der Version 2.0.0 funktioniert?

**Comment by tp1de** [comment]
Funktioniert leider nicht. Datenpunkt ist writable = true, aber ich kann keinen Wert setzen. 
Übrigens stimmt auch der aktuelle Status (value-Feld) nicht. 
Steht auf on, obwohl ausgeschaltet.

**Comment by t4qjXH8N** [comment]
Hey, das ist blöd. Kannst Du mir das JSON schicken, dass von Gardena kommt? Das gänge z.B. mit Sniffer für Android. Am besten per Email an chvorholt@gmail.com, es muss ja nicht jeder den Inhalt sehen.
